### ISSUE TITLE
Not found: Op type not registered 'HashTableV2' 

### ISSUE THREAD

**Issue by ljch2018** [formath/tensorflow-predictor-cpp#10]
any idea?

**Comment by aimetrics** [comment]
I have the same error: 

> Session created successfully
Load graph protobuf successfully
Not found: Op type not registered 'HashTableV2' in binary running on Titan GPU, tf1.14. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by aimetrics** [comment]
@mmmwhy How did you fix this error?

**Comment by formath** [comment]
Add `HashTableV2` to `tensorflow/contrib/makefile/tf_op_files.txt` and compile tensorflow from source code.

**Comment by aimetrics** [comment]
> Add `HashTableV2` to `tensorflow/contrib/makefile/tf_op_files.txt` and compile tensorflow from source code.

Thanks for your quickly reply. It works!
`tensorflow/core/ops/lookup_ops.cc
tensorflow/core/kernels/as_string_op.cc
tensorflow/core/kernels/string_to_hash_bucket_op.cc
`
