### ISSUE TITLE
tensorflow/core/framework/variant_encode_decode.h: No such file or directory

### ISSUE THREAD

**Issue by supernan** [formath/tensorflow-predictor-cpp#2]
运行make命令时，报错：tensorflow/core/framework/variant_encode_decode.h: No such file or directory 。 项目的目录与tensorflow平级，进入tensorflow/core/framework/中也发现没有这个头文件，请问这个问题该如何处理

**Comment by formath** [comment]
the directory should be
```
- tensorflow
  - tensorflow
    - core
- tensorflow-predictor-cpp
```
