### ISSUE TITLE
Not found: Op type not registered 'HashTableV2'

### ISSUE THREAD

**Issue by mmmwhy** [formath/tensorflow-predictor-cpp#7]
`sh predict.sh`

Session created successfully
Load graph protobuf successfully
Not found: Op type not registered 'HashTableV2' in binary running on MacBook-Pro.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

环境：
tensorflow 1.8
python 3.6

**Comment by mmmwhy** [comment]
Not found: Op type not registered 'HashTableV2' in binary running on MacBook-Pro.local. 
Make sure the Op and Kernel are registered in the binary running in this process. 
Note that if you are loading a saved graph which used ops from tf.contrib, 
accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, 
as contrib ops are lazily registered when the module is first accessed.

**Comment by mmmwhy** [comment]
it seems the codes need to change somehow

**Comment by mmmwhy** [comment]
已尝试使用 https://github.com/formath/tensorflow.git   branch: fix 编译，还是报错。

**Comment by formath** [comment]
What is the error using `branch: fix`?

**Comment by mmmwhy** [comment]
i have rewritten this inference part, thank you.

**Comment by mjjdick** [comment]
@mmmwhy @formath I met the same error! 
environment:
tensorflow 1.10
python 2.7
it seems the bug about sparse tensor? can you guys help me? thx very much!

**Comment by xixiddd** [comment]
the same problem using "fix" branch

> Session created successfully
Load graph protobuf successfully
Not found: Op type not registered 'HashTableV2' in binary running on a00bbeef0667. Make sure the Op and Kernel are registered in the binary running inthis process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done beforeimporting the graph, as contrib ops are lazily registered when the module is first accessed.

and I have read through all Issues about this problem, but just not solved yet.
